/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_nano_server_MainActivity */

#ifndef _Included_com_example_administrator_nano_server_MainActivity
#define _Included_com_example_administrator_nano_server_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_nano_server_MainActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_nano_1server_MainActivity_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_administrator_nano_server_MainActivity
 * Method:    createAudioPlayer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_administrator_nano_1server_MainActivity_createAudioPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_administrator_nano_server_MainActivity
 * Method:    setPlayingAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_nano_1server_MainActivity_setPlayingAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_administrator_nano_server_MainActivity
 * Method:    setVolumeAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_nano_1server_MainActivity_setVolumeAudioPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_administrator_nano_server_MainActivity
 * Method:    setMutAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_nano_1server_MainActivity_setMutAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_administrator_nano_server_MainActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_nano_1server_MainActivity_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
